<?php

namespace AppBundle\Repository;

/**
 * CRUDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CRUDRepository extends \Doctrine\ORM\EntityRepository
{
}
